name: Bug Report
description: 발견된 버그를 보고합니다.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: epic
    attributes:
      label: "🔗 연관된 Epic Issue"
      description: "이 버그가 속하는 Epic Issue 번호를 입력하세요 (예: #10)"
      placeholder: "#EpicIssueNumber"

  - type: textarea
    id: bug_description
    attributes:
      label: "🐛 버그 설명"
      description: "어떤 문제가 발생했는지 설명해주세요."
  
