name: Edit Document
description: 기존 기능을 개선하는 요청을 작성합니다.
title: "[Enhance]: "
labels: ["document"]
body:
  - type: input
    id: epic
    attributes:
      label: "🔗 연관된 Epic Issue"
      description: "이 수정사항이 속하는 Epic Issue 번호를 입력하세요 (예: #10)"
      placeholder: "#EpicIssueNumber"

  - type: textarea
    id: document_description
    attributes:
      label: "✨ 수정할 문서 내용"
      description: "어떤 부분을 수정 하는지 설명해주세요."
